### ISSUE TITLE
SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by iiONE** [04x/instagramBrute#2]
![Screenshot_24](https://user-images.githubusercontent.com/16639277/85231864-4db79580-b403-11ea-8bb8-9fc17aed731b.png)
Does anyone have a solution ?

**Comment by BADINVINCIBLE** [comment]
> ![Screenshot_24](https://user-images.githubusercontent.com/16639277/85231864-4db79580-b403-11ea-8bb8-9fc17aed731b.png)
> Does anyone have a solutu

> ![Screenshot_24](https://user-images.githubusercontent.com/16639277/85231864-4db79580-b403-11ea-8bb8-9fc17aed731b.png)
> Does anyone have a solution ?

Use the command python without 3

**Comment by 8x-chris** [comment]
how do u get instagram passwords with this tool?
